# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'reactIon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reactIon
	pod 'Firebase'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Core'
	pod 'Firebase/Firestore'

  target 'reactIonTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reactIonUITests' do
    # Pods for testing
  end

end
